name: flutter_translate_gen
description: Statically-typed localization keys generator for flutter_translate.
version: 1.2.4
author: Florin Bratan <florin@leadcode.dev>
homepage: https://leadcode.dev
repository: https://github.com/bratan/flutter_translate_gen

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_casing:
    git: https://github.com/McCrafterIV/dart_casing
  dart_utils:
    git: https://github.com/McCrafterIV/dart_utils
  source_gen: ^1.0.1
  build: ^2.0.2
  code_builder: ^4.0.0
  glob: ^2.0.1
  # TODO point to 1.0.2 as soon as it is merged
  flutter_translate_annotations:
    git:
      url: https://github.com/avbk/flutter_translate_annotations
      ref: nullsafe


dev_dependencies:
  build_runner: ^2.0.4
  lint: ^1.5.3
  test: ^1.17.5
